# Generated by Django 5.1.4 on 2024-12-27 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generic', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='genericpage',
            name='introduction',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='genericpage',
            name='banner_title',
            field=models.CharField(default='Welcome to my generic page!', max_length=100),
        ),
    ]
