# Generated by Django 5.1.4 on 2024-12-27 10:32

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('generic', '0006_genericpage_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genericpage',
            name='body',
            field=wagtail.fields.StreamField([('heading', 0), ('image', 1), ('paragraph', 2)], block_lookup={0: ('wagtail.blocks.CharBlock', (), {'template': 'heading_block.html'}), 1: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 2: ('wagtail.blocks.RichTextBlock', (), {})}, null=True),
        ),
    ]
